# Mark Shust's Magento 2 Docker Compose (https://github.com/markoshust/magento2-docker)
# Version 10.0.0

version: "3"

services:
  app:
    image: markoshust/magento2-nginx:1.13-0
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - appdata:/var/www/html
    ports:
      - 8000:80
    networks: &appnetworks
      - www

  phpfpm:
    image: mageinferno/magento2-php:7.0-fpm-1 # change this to 5.6-fpm-1 if magento 1.9
    links:
      - db
    volumes: *appvolumes
    networks: *appnetworks

  db:
    image: percona:5.7
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 8001:3306
    networks: *appnetworks
    env_file: env/mysql.env

  setup:
    image: mageinferno/magento2-php:7.0-fpm-1 # change this to 5.6-fpm-1 if magento 1.9
    command: /usr/local/bin/mage-setup
    links:
      - db
    volumes: *appvolumes
    networks: *appnetworks
    env_file: env/setup.env

volumes:
  dbdata:
  appdata:

networks:
  www:
